export const designTokens = {
  colors: {
    surface: '#ffffff',
    surfaceDim: '#cbdbf5',
    surfaceBright: '#f8f9ff',
    onSurface: '#0b1c30',
    onSurfaceVariant: '#45464d',
    outline: '#76777d',
    outlineVariant: '#c6c6cd',
    primary: '#0f172a',
    onPrimary: '#ffffff',
    secondary: '#3b82f6',
    onSecondary: '#ffffff',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    background: '#f8faFc',
    onBackground: '#0b1c30',
  },
  typography: {
    displayLg: { fontFamily: 'System', fontSize: 32, fontWeight: '700' as const, lineHeight: 40 },
    headlineMd: { fontFamily: 'System', fontSize: 24, fontWeight: '600' as const, lineHeight: 32 },
    headlineSm: { fontFamily: 'System', fontSize: 20, fontWeight: '600' as const, lineHeight: 28 },
    titleLg: { fontFamily: 'System', fontSize: 18, fontWeight: '600' as const, lineHeight: 24 },
    bodyLg: { fontFamily: 'System', fontSize: 16, fontWeight: '400' as const, lineHeight: 24 },
    bodyMd: { fontFamily: 'System', fontSize: 14, fontWeight: '400' as const, lineHeight: 20 },
    labelMd: { fontFamily: 'System', fontSize: 12, fontWeight: '500' as const, lineHeight: 16 },
    labelSm: { fontFamily: 'System', fontSize: 11, fontWeight: '600' as const, lineHeight: 14 },
  },
  rounded: {
    sm: 4,
    DEFAULT: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  spacing: {
    base: 4,
    marginMobile: 16,
    gutter: 12,
    stackSm: 8,
    stackMd: 16,
    stackLg: 24,
  }
};
